export const data = [
  {
    id: 1,
    task: "Design landing page",
    description:
      "Create wireframes and design mockups for the landing page of the website.",
    start_date: "2024-03-23",
    end_date: "",
    status: "In Progress",
    assignee: "John Doe",
    priority: "P1",
  },
  {
    id: 2,
    task: "Implement user authentication",
    description:
      "Set up user authentication system using JWT for secure access to the application.",
    start_date: "2024-03-22",
    end_date: "",
    status: "Pending",
    assignee: "Jane Smith",
    priority: "P2",
  },
  {
    id: 3,
    task: "Fix bug in dashboard",
    description:
      "Investigate and resolve issue causing incorrect data rendering in the dashboard module.",
    start_date: "2024-03-24",
    end_date: "",
    status: "Pending",
    assignee: "Alice Johnson",
    priority: "P1",
  },
  {
    id: 4,
    task: "Deploy backend API",
    description:
      "Deploy the latest version of the backend API to the production server.",
    start_date: "2024-03-20",
    end_date: "2024-03-25",
    status: "Completed",
    assignee: "Mark Wilson",
    priority: "P0",
  },
  {
    id: 5,
    task: "Update documentation",
    description:
      "Update user and developer documentation to reflect recent changes in the application.",
    start_date: "2024-03-21",
    end_date: "",
    status: "Deferred",
    assignee: "Emily Brown",
    priority: "P2",
  },
  {
    id: 6,
    task: "Refactor codebase",
    description:
      "Perform code refactoring to improve code maintainability and readability.",
    start_date: "2024-03-25",
    end_date: "",
    status: "In Progress",
    assignee: "Alex Johnson",
    priority: "P1",
  },
  {
    id: 7,
    task: "Add unit tests",
    description:
      "Write unit tests for critical components of the application to ensure code reliability.",
    start_date: "2024-03-26",
    end_date: "",
    status: "Pending",
    assignee: "Chris Evans",
    priority: "P2",
  },
  {
    id: 8,
    task: "Optimize database queries",
    description:
      "Identify and optimize slow database queries to improve application performance.",
    start_date: "2024-03-27",
    end_date: "",
    status: "Pending",
    assignee: "Sarah Parker",
    priority: "P1",
  },
  {
    id: 9,
    task: "Create admin dashboard",
    description:
      "Develop an admin dashboard with features for managing user accounts and permissions.",
    start_date: "2024-03-28",
    end_date: "",
    status: "Pending",
    assignee: "Michael Johnson",
    priority: "P1",
  },
  {
    id: 10,
    task: "Write API documentation",
    description:
      "Document API endpoints and usage guidelines for external developers.",
    start_date: "2024-03-29",
    end_date: "",
    status: "Pending",
    assignee: "Jennifer Lee",
    priority: "P2",
  },
  {
    id: 11,
    task: "Fix responsive layout issues",
    description:
      "Address layout issues affecting the responsiveness of the application across different devices.",
    start_date: "2024-03-30",
    end_date: "",
    status: "Pending",
    assignee: "Daniel Brown",
    priority: "P1",
  },
  {
    id: 12,
    task: "Update branding assets",
    description:
      "Update logos, icons, and other branding assets to align with the latest brand guidelines.",
    start_date: "2024-03-31",
    end_date: "",
    status: "Pending",
    assignee: "Jessica Miller",
    priority: "P2",
  },
  {
    id: 13,
    task: "Perform security audit",
    description:
      "Conduct a security audit to identify and address vulnerabilities in the application.",
    start_date: "2024-04-01",
    end_date: "",
    status: "Pending",
    assignee: "David Wilson",
    priority: "P0",
  },
  {
    id: 14, 
    task: "Integrate payment gateway",
    description:
      "Integrate a payment gateway for processing transactions within the application.",
    start_date: "2024-04-02",
    end_date: "",
    status: "Pending",
    assignee: "Olivia Taylor",
    priority: "P1",
  },
  {
    id: 15,
    task: "Create user onboarding flow",
    description:
      "Design and implement a user onboarding flow to guide new users through the application.",
    start_date: "2024-04-03",
    end_date: "",
    status: "Pending",
    assignee: "William Johnson",
    priority: "P2",
  },
  {
    id: 16,
    task: "Optimize front-end performance",
    description:
      "Optimize front-end code and assets to reduce page load times and improve user experience.",
    start_date: "2024-04-04",
    end_date: "",
    status: "Pending",
    assignee: "Emma Brown",
    priority: "P1",
  },
  {
    id: 17,
    task: "Create user feedback form",
    description:
      "Implement a user feedback form to gather feedback and suggestions from users.",
    start_date: "2024-04-05",
    end_date: "",
    status: "Pending",
    assignee: "Noah Johnson",
    priority: "P2",
  },
  {
    id: 18,
    task: "Set up continuous integration",
    description:
      "Configure continuous integration and deployment pipelines for automated testing and deployment.",
    start_date: "2024-04-06",
    end_date: "",
    status: "Pending",
    assignee: "Sophia Brown",
    priority: "P1",
  },
  {
    id: 19,
    task: "Implement search functionality",
    description:
      "Add search functionality to allow users to search for specific content within the application.",
    start_date: "2024-04-07",
    end_date: "",
    status: "Pending",
    assignee: "James Johnson",
    priority: "P2",
  },
  {
    id: 20,
    task: "Update terms of service",
    description:
      "Review and update the terms of service document to reflect changes in the application.",
    start_date: "2024-04-08",
    end_date: "",
    status: "Pending",
    assignee: "Ava Brown",
    priority: "P1",
  },
];